# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import argocd_client
from argocd_client.models.v1alpha1_sync_strategy import V1alpha1SyncStrategy  # noqa: E501
from argocd_client.rest import ApiException

class TestV1alpha1SyncStrategy(unittest.TestCase):
    """V1alpha1SyncStrategy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1alpha1SyncStrategy
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = argocd_client.models.v1alpha1_sync_strategy.V1alpha1SyncStrategy()  # noqa: E501
        if include_optional :
            return V1alpha1SyncStrategy(
                apply = argocd_client.models.sync_strategy_apply_uses_`kubectl_apply`_to_perform_the_apply.SyncStrategyApply uses `kubectl apply` to perform the apply(
                    force = True, ), 
                hook = argocd_client.models.v1alpha1_sync_strategy_hook.v1alpha1SyncStrategyHook(
                    sync_strategy_apply = argocd_client.models.sync_strategy_apply_uses_`kubectl_apply`_to_perform_the_apply.SyncStrategyApply uses `kubectl apply` to perform the apply(
                        force = True, ), )
            )
        else :
            return V1alpha1SyncStrategy(
        )

    def testV1alpha1SyncStrategy(self):
        """Test V1alpha1SyncStrategy"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
