# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import argocd_client
from argocd_client.api.application_service_api import ApplicationServiceApi  # noqa: E501
from argocd_client.rest import ApiException


class TestApplicationServiceApi(unittest.TestCase):
    """ApplicationServiceApi unit test stubs"""

    def setUp(self):
        self.api = argocd_client.api.application_service_api.ApplicationServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_mixin9(self):
        """Test case for create_mixin9

        Create creates an application  # noqa: E501
        """
        pass

    def test_delete_mixin9(self):
        """Test case for delete_mixin9

        Delete deletes an application  # noqa: E501
        """
        pass

    def test_delete_resource(self):
        """Test case for delete_resource

        DeleteResource deletes a single application resource  # noqa: E501
        """
        pass

    def test_get_application_sync_windows(self):
        """Test case for get_application_sync_windows

        Get returns an application by name  # noqa: E501
        """
        pass

    def test_get_manifests(self):
        """Test case for get_manifests

        GetManifests returns application manifests  # noqa: E501
        """
        pass

    def test_get_mixin9(self):
        """Test case for get_mixin9

        Get returns an application by name  # noqa: E501
        """
        pass

    def test_get_resource(self):
        """Test case for get_resource

        GetResource returns single application resource  # noqa: E501
        """
        pass

    def test_list_mixin9(self):
        """Test case for list_mixin9

        List returns list of applications  # noqa: E501
        """
        pass

    def test_list_resource_actions(self):
        """Test case for list_resource_actions

        """
        pass

    def test_list_resource_events(self):
        """Test case for list_resource_events

        ListResourceEvents returns a list of event resources  # noqa: E501
        """
        pass

    def test_managed_resources(self):
        """Test case for managed_resources

        """
        pass

    def test_patch(self):
        """Test case for patch

        Patch patch an application  # noqa: E501
        """
        pass

    def test_patch_resource(self):
        """Test case for patch_resource

        PatchResource patch single application resource  # noqa: E501
        """
        pass

    def test_pod_logs(self):
        """Test case for pod_logs

        PodLogs returns stream of log entries for the specified pod. Pod  # noqa: E501
        """
        pass

    def test_resource_tree(self):
        """Test case for resource_tree

        """
        pass

    def test_revision_metadata(self):
        """Test case for revision_metadata

        Get the meta-data (author, date, tags, message) for a specific revision of the application  # noqa: E501
        """
        pass

    def test_rollback(self):
        """Test case for rollback

        Rollback syncs an application to its target state  # noqa: E501
        """
        pass

    def test_run_resource_action(self):
        """Test case for run_resource_action

        """
        pass

    def test_sync(self):
        """Test case for sync

        Sync syncs an application to its target state  # noqa: E501
        """
        pass

    def test_terminate_operation(self):
        """Test case for terminate_operation

        TerminateOperation terminates the currently running operation  # noqa: E501
        """
        pass

    def test_update_mixin9(self):
        """Test case for update_mixin9

        Update updates an application  # noqa: E501
        """
        pass

    def test_update_spec(self):
        """Test case for update_spec

        UpdateSpec updates an application spec  # noqa: E501
        """
        pass

    def test_watch(self):
        """Test case for watch

        Watch returns stream of application change events.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
