# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import argocd_client
from argocd_client.models.v1alpha1_sync_strategy_hook import V1alpha1SyncStrategyHook  # noqa: E501
from argocd_client.rest import ApiException

class TestV1alpha1SyncStrategyHook(unittest.TestCase):
    """V1alpha1SyncStrategyHook unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1alpha1SyncStrategyHook
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = argocd_client.models.v1alpha1_sync_strategy_hook.V1alpha1SyncStrategyHook()  # noqa: E501
        if include_optional :
            return V1alpha1SyncStrategyHook(
                sync_strategy_apply = argocd_client.models.sync_strategy_apply_uses_`kubectl_apply`_to_perform_the_apply.SyncStrategyApply uses `kubectl apply` to perform the apply(
                    force = True, )
            )
        else :
            return V1alpha1SyncStrategyHook(
        )

    def testV1alpha1SyncStrategyHook(self):
        """Test V1alpha1SyncStrategyHook"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
