# coding: utf-8
# Copyright (c) 2020, Globo (https://github.com/globocom)
# License: BSD-3-Clause

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import argocd_client
from argocd_client.api.settings_service_api import SettingsServiceApi  # noqa: E501
from argocd_client.rest import ApiException


class TestSettingsServiceApi(unittest.TestCase):
    """SettingsServiceApi unit test stubs"""

    def setUp(self):
        self.api = argocd_client.api.settings_service_api.SettingsServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get(self):
        """Test case for get

        Get returns Argo CD settings  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
