# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import argocd_client
from argocd_client.models.v1alpha1_repository_certificate_list import V1alpha1RepositoryCertificateList  # noqa: E501
from argocd_client.rest import ApiException

class TestV1alpha1RepositoryCertificateList(unittest.TestCase):
    """V1alpha1RepositoryCertificateList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1alpha1RepositoryCertificateList
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = argocd_client.models.v1alpha1_repository_certificate_list.V1alpha1RepositoryCertificateList()  # noqa: E501
        if include_optional :
            return V1alpha1RepositoryCertificateList(
                items = [
                    argocd_client.models.a_repository_certificate_is_either_ssh_known_hosts_entry_or_tls_certificate.A RepositoryCertificate is either SSH known hosts entry or TLS certificate(
                        cert_data = 'YQ==', 
                        cert_info = '0', 
                        cert_sub_type = '0', 
                        cert_type = '0', 
                        server_name = '0', )
                    ], 
                metadata = argocd_client.models.v1_list_meta.v1ListMeta(
                    continue = '0', 
                    remaining_item_count = '0', 
                    resource_version = '0', 
                    self_link = '0', )
            )
        else :
            return V1alpha1RepositoryCertificateList(
        )

    def testV1alpha1RepositoryCertificateList(self):
        """Test V1alpha1RepositoryCertificateList"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
