# coding: utf-8
# Copyright (c) 2020, Globo (https://github.com/globocom)
# License: BSD-3-Clause

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import argocd_client
from argocd_client.models.gpgkey_gnu_pg_public_key_create_response import GpgkeyGnuPGPublicKeyCreateResponse  # noqa: E501
from argocd_client.rest import ApiException

class TestGpgkeyGnuPGPublicKeyCreateResponse(unittest.TestCase):
    """GpgkeyGnuPGPublicKeyCreateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GpgkeyGnuPGPublicKeyCreateResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = argocd_client.models.gpgkey_gnu_pg_public_key_create_response.GpgkeyGnuPGPublicKeyCreateResponse()  # noqa: E501
        if include_optional :
            return GpgkeyGnuPGPublicKeyCreateResponse(
                created = argocd_client.models.gnu_pg_public_key_list_is_a_collection_of_gnu_pg_public_key_objects.GnuPGPublicKeyList is a collection of GnuPGPublicKey objects(
                    items = [
                        argocd_client.models.gnu_pg_public_key_is_a_representation_of_a_gnu_pg_public_key.GnuPGPublicKey is a representation of a GnuPG public key(
                            fingerprint = '0', 
                            key_data = '0', 
                            key_id = '0', 
                            owner = '0', 
                            sub_type = '0', 
                            trust = '0', )
                        ], 
                    metadata = argocd_client.models.v1_list_meta.v1ListMeta(
                        continue = '0', 
                        remaining_item_count = '0', 
                        resource_version = '0', 
                        self_link = '0', ), ), 
                skipped = [
                    '0'
                    ]
            )
        else :
            return GpgkeyGnuPGPublicKeyCreateResponse(
        )

    def testGpgkeyGnuPGPublicKeyCreateResponse(self):
        """Test GpgkeyGnuPGPublicKeyCreateResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
