# coding: utf-8
# Copyright (c) 2020, Globo (https://github.com/globocom)
# License: BSD-3-Clause

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import argocd_client
from argocd_client.models.repository_manifest_response import RepositoryManifestResponse  # noqa: E501
from argocd_client.rest import ApiException

class TestRepositoryManifestResponse(unittest.TestCase):
    """RepositoryManifestResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test RepositoryManifestResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = argocd_client.models.repository_manifest_response.RepositoryManifestResponse()  # noqa: E501
        if include_optional :
            return RepositoryManifestResponse(
                manifests = [
                    '0'
                    ], 
                namespace = '0', 
                revision = '0', 
                server = '0', 
                source_type = '0', 
                verify_result = '0'
            )
        else :
            return RepositoryManifestResponse(
        )

    def testRepositoryManifestResponse(self):
        """Test RepositoryManifestResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
