# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import argocd_client
from argocd_client.models.v1alpha1_project_role import V1alpha1ProjectRole  # noqa: E501
from argocd_client.rest import ApiException

class TestV1alpha1ProjectRole(unittest.TestCase):
    """V1alpha1ProjectRole unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1alpha1ProjectRole
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = argocd_client.models.v1alpha1_project_role.V1alpha1ProjectRole()  # noqa: E501
        if include_optional :
            return V1alpha1ProjectRole(
                description = '0', 
                groups = [
                    '0'
                    ], 
                jwt_tokens = [
                    argocd_client.models.jwt_token_holds_the_issued_at_and_expires_at_values_of_a_token.JWTToken holds the issuedAt and expiresAt values of a token(
                        exp = '0', 
                        iat = '0', 
                        id = '0', )
                    ], 
                name = '0', 
                policies = [
                    '0'
                    ]
            )
        else :
            return V1alpha1ProjectRole(
        )

    def testV1alpha1ProjectRole(self):
        """Test V1alpha1ProjectRole"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
