# coding: utf-8
# Copyright (c) 2020, Globo (https://github.com/globocom)
# License: BSD-3-Clause

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import argocd_client
from argocd_client.models.v1alpha1_app_project_status import V1alpha1AppProjectStatus  # noqa: E501
from argocd_client.rest import ApiException

class TestV1alpha1AppProjectStatus(unittest.TestCase):
    """V1alpha1AppProjectStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1alpha1AppProjectStatus
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = argocd_client.models.v1alpha1_app_project_status.V1alpha1AppProjectStatus()  # noqa: E501
        if include_optional :
            return V1alpha1AppProjectStatus(
                jwt_tokens_by_role = {
                    'key' : argocd_client.models.v1alpha1_jwt_tokens.v1alpha1JWTTokens(
                        items = [
                            argocd_client.models.jwt_token_holds_the_issued_at_and_expires_at_values_of_a_token.JWTToken holds the issuedAt and expiresAt values of a token(
                                exp = '0', 
                                iat = '0', 
                                id = '0', )
                            ], )
                    }
            )
        else :
            return V1alpha1AppProjectStatus(
        )

    def testV1alpha1AppProjectStatus(self):
        """Test V1alpha1AppProjectStatus"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
