# coding: utf-8
# Copyright (c) 2020, Globo (https://github.com/globocom)
# License: BSD-3-Clause

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import argocd_client
from argocd_client.models.v1_object_meta import V1ObjectMeta  # noqa: E501
from argocd_client.rest import ApiException

class TestV1ObjectMeta(unittest.TestCase):
    """V1ObjectMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1ObjectMeta
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = argocd_client.models.v1_object_meta.V1ObjectMeta()  # noqa: E501
        if include_optional :
            return V1ObjectMeta(
                annotations = {
                    'key' : '0'
                    }, 
                cluster_name = '0', 
                creation_timestamp = argocd_client.models.v1_time.v1Time(
                    nanos = 56, 
                    seconds = '0', ), 
                deletion_grace_period_seconds = '0', 
                deletion_timestamp = argocd_client.models.v1_time.v1Time(
                    nanos = 56, 
                    seconds = '0', ), 
                finalizers = [
                    '0'
                    ], 
                generate_name = '0', 
                generation = '0', 
                labels = {
                    'key' : '0'
                    }, 
                managed_fields = [
                    argocd_client.models.v1_managed_fields_entry.v1ManagedFieldsEntry(
                        api_version = '0', 
                        fields_type = '0', 
                        fields_v1 = argocd_client.models.v1_fields_v1.v1FieldsV1(
                            raw = 'YQ==', ), 
                        manager = '0', 
                        operation = '0', 
                        time = argocd_client.models.v1_time.v1Time(
                            nanos = 56, 
                            seconds = '0', ), )
                    ], 
                name = '0', 
                namespace = '0', 
                owner_references = [
                    argocd_client.models.v1_owner_reference.v1OwnerReference(
                        api_version = '0', 
                        block_owner_deletion = True, 
                        controller = True, 
                        kind = '0', 
                        name = '0', 
                        uid = '0', )
                    ], 
                resource_version = '0', 
                self_link = '0', 
                uid = '0'
            )
        else :
            return V1ObjectMeta(
        )

    def testV1ObjectMeta(self):
        """Test V1ObjectMeta"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
