# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import argocd_client
from argocd_client.models.v1alpha1_info_item import V1alpha1InfoItem  # noqa: E501
from argocd_client.rest import ApiException

class TestV1alpha1InfoItem(unittest.TestCase):
    """V1alpha1InfoItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1alpha1InfoItem
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = argocd_client.models.v1alpha1_info_item.V1alpha1InfoItem()  # noqa: E501
        if include_optional :
            return V1alpha1InfoItem(
                name = '0', 
                value = '0'
            )
        else :
            return V1alpha1InfoItem(
        )

    def testV1alpha1InfoItem(self):
        """Test V1alpha1InfoItem"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
