# coding: utf-8
# Copyright (c) 2020, Globo (https://github.com/globocom)
# License: BSD-3-Clause

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import argocd_client
from argocd_client.api.gpg_key_service_api import GPGKeyServiceApi  # noqa: E501
from argocd_client.rest import ApiException


class TestGPGKeyServiceApi(unittest.TestCase):
    """GPGKeyServiceApi unit test stubs"""

    def setUp(self):
        self.api = argocd_client.api.gpg_key_service_api.GPGKeyServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_mixin7(self):
        """Test case for create_mixin7

        Create one or more GPG public keys in the server's configuration  # noqa: E501
        """
        pass

    def test_delete_mixin7(self):
        """Test case for delete_mixin7

        Delete specified GPG public key from the server's configuration  # noqa: E501
        """
        pass

    def test_get_mixin7(self):
        """Test case for get_mixin7

        Get information about specified GPG public key from the server  # noqa: E501
        """
        pass

    def test_list_mixin7(self):
        """Test case for list_mixin7

        List all available repository certificates  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
