# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import argocd_client
from argocd_client.models.v1alpha1_revision_metadata import V1alpha1RevisionMetadata  # noqa: E501
from argocd_client.rest import ApiException

class TestV1alpha1RevisionMetadata(unittest.TestCase):
    """V1alpha1RevisionMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1alpha1RevisionMetadata
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = argocd_client.models.v1alpha1_revision_metadata.V1alpha1RevisionMetadata()  # noqa: E501
        if include_optional :
            return V1alpha1RevisionMetadata(
                author = '0', 
                date = argocd_client.models.v1_time.v1Time(
                    nanos = 56, 
                    seconds = '0', ), 
                message = '0', 
                signature_info = '0', 
                tags = [
                    '0'
                    ]
            )
        else :
            return V1alpha1RevisionMetadata(
        )

    def testV1alpha1RevisionMetadata(self):
        """Test V1alpha1RevisionMetadata"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
