# coding: utf-8
# Copyright (c) 2020, Globo (https://github.com/globocom)
# License: BSD-3-Clause

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from argocd_client.configuration import Configuration


class RepositoryKsonnetAppSpec(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'environments': 'dict(str, RepositoryKsonnetEnvironment)',
        'name': 'str',
        'parameters': 'list[V1alpha1KsonnetParameter]'
    }

    attribute_map = {
        'environments': 'environments',
        'name': 'name',
        'parameters': 'parameters'
    }

    def __init__(self, environments=None, name=None, parameters=None, local_vars_configuration=None):  # noqa: E501
        """RepositoryKsonnetAppSpec - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._environments = None
        self._name = None
        self._parameters = None
        self.discriminator = None

        if environments is not None:
            self.environments = environments
        if name is not None:
            self.name = name
        if parameters is not None:
            self.parameters = parameters

    @property
    def environments(self):
        """Gets the environments of this RepositoryKsonnetAppSpec.  # noqa: E501


        :return: The environments of this RepositoryKsonnetAppSpec.  # noqa: E501
        :rtype: dict(str, RepositoryKsonnetEnvironment)
        """
        return self._environments

    @environments.setter
    def environments(self, environments):
        """Sets the environments of this RepositoryKsonnetAppSpec.


        :param environments: The environments of this RepositoryKsonnetAppSpec.  # noqa: E501
        :type: dict(str, RepositoryKsonnetEnvironment)
        """

        self._environments = environments

    @property
    def name(self):
        """Gets the name of this RepositoryKsonnetAppSpec.  # noqa: E501


        :return: The name of this RepositoryKsonnetAppSpec.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this RepositoryKsonnetAppSpec.


        :param name: The name of this RepositoryKsonnetAppSpec.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def parameters(self):
        """Gets the parameters of this RepositoryKsonnetAppSpec.  # noqa: E501


        :return: The parameters of this RepositoryKsonnetAppSpec.  # noqa: E501
        :rtype: list[V1alpha1KsonnetParameter]
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters):
        """Sets the parameters of this RepositoryKsonnetAppSpec.


        :param parameters: The parameters of this RepositoryKsonnetAppSpec.  # noqa: E501
        :type: list[V1alpha1KsonnetParameter]
        """

        self._parameters = parameters

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RepositoryKsonnetAppSpec):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RepositoryKsonnetAppSpec):
            return True

        return self.to_dict() != other.to_dict()
