# coding: utf-8
# Copyright (c) 2020, Globo (https://github.com/globocom)
# License: BSD-3-Clause

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from argocd_client.configuration import Configuration


class V1alpha1RepoCreds(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'password': 'str',
        'ssh_private_key': 'str',
        'tls_client_cert_data': 'str',
        'tls_client_cert_key': 'str',
        'url': 'str',
        'username': 'str'
    }

    attribute_map = {
        'password': 'password',
        'ssh_private_key': 'sshPrivateKey',
        'tls_client_cert_data': 'tlsClientCertData',
        'tls_client_cert_key': 'tlsClientCertKey',
        'url': 'url',
        'username': 'username'
    }

    def __init__(self, password=None, ssh_private_key=None, tls_client_cert_data=None, tls_client_cert_key=None, url=None, username=None, local_vars_configuration=None):  # noqa: E501
        """V1alpha1RepoCreds - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._password = None
        self._ssh_private_key = None
        self._tls_client_cert_data = None
        self._tls_client_cert_key = None
        self._url = None
        self._username = None
        self.discriminator = None

        if password is not None:
            self.password = password
        if ssh_private_key is not None:
            self.ssh_private_key = ssh_private_key
        if tls_client_cert_data is not None:
            self.tls_client_cert_data = tls_client_cert_data
        if tls_client_cert_key is not None:
            self.tls_client_cert_key = tls_client_cert_key
        if url is not None:
            self.url = url
        if username is not None:
            self.username = username

    @property
    def password(self):
        """Gets the password of this V1alpha1RepoCreds.  # noqa: E501


        :return: The password of this V1alpha1RepoCreds.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this V1alpha1RepoCreds.


        :param password: The password of this V1alpha1RepoCreds.  # noqa: E501
        :type: str
        """

        self._password = password

    @property
    def ssh_private_key(self):
        """Gets the ssh_private_key of this V1alpha1RepoCreds.  # noqa: E501


        :return: The ssh_private_key of this V1alpha1RepoCreds.  # noqa: E501
        :rtype: str
        """
        return self._ssh_private_key

    @ssh_private_key.setter
    def ssh_private_key(self, ssh_private_key):
        """Sets the ssh_private_key of this V1alpha1RepoCreds.


        :param ssh_private_key: The ssh_private_key of this V1alpha1RepoCreds.  # noqa: E501
        :type: str
        """

        self._ssh_private_key = ssh_private_key

    @property
    def tls_client_cert_data(self):
        """Gets the tls_client_cert_data of this V1alpha1RepoCreds.  # noqa: E501


        :return: The tls_client_cert_data of this V1alpha1RepoCreds.  # noqa: E501
        :rtype: str
        """
        return self._tls_client_cert_data

    @tls_client_cert_data.setter
    def tls_client_cert_data(self, tls_client_cert_data):
        """Sets the tls_client_cert_data of this V1alpha1RepoCreds.


        :param tls_client_cert_data: The tls_client_cert_data of this V1alpha1RepoCreds.  # noqa: E501
        :type: str
        """

        self._tls_client_cert_data = tls_client_cert_data

    @property
    def tls_client_cert_key(self):
        """Gets the tls_client_cert_key of this V1alpha1RepoCreds.  # noqa: E501


        :return: The tls_client_cert_key of this V1alpha1RepoCreds.  # noqa: E501
        :rtype: str
        """
        return self._tls_client_cert_key

    @tls_client_cert_key.setter
    def tls_client_cert_key(self, tls_client_cert_key):
        """Sets the tls_client_cert_key of this V1alpha1RepoCreds.


        :param tls_client_cert_key: The tls_client_cert_key of this V1alpha1RepoCreds.  # noqa: E501
        :type: str
        """

        self._tls_client_cert_key = tls_client_cert_key

    @property
    def url(self):
        """Gets the url of this V1alpha1RepoCreds.  # noqa: E501


        :return: The url of this V1alpha1RepoCreds.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this V1alpha1RepoCreds.


        :param url: The url of this V1alpha1RepoCreds.  # noqa: E501
        :type: str
        """

        self._url = url

    @property
    def username(self):
        """Gets the username of this V1alpha1RepoCreds.  # noqa: E501


        :return: The username of this V1alpha1RepoCreds.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this V1alpha1RepoCreds.


        :param username: The username of this V1alpha1RepoCreds.  # noqa: E501
        :type: str
        """

        self._username = username

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1RepoCreds):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1alpha1RepoCreds):
            return True

        return self.to_dict() != other.to_dict()
