# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from argocd_client.configuration import Configuration


class V1alpha1ApplicationSourceKustomize(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'common_labels': 'dict(str, str)',
        'images': 'list[str]',
        'name_prefix': 'str',
        'name_suffix': 'str',
        'version': 'str'
    }

    attribute_map = {
        'common_labels': 'commonLabels',
        'images': 'images',
        'name_prefix': 'namePrefix',
        'name_suffix': 'nameSuffix',
        'version': 'version'
    }

    def __init__(self, common_labels=None, images=None, name_prefix=None, name_suffix=None, version=None, local_vars_configuration=None):  # noqa: E501
        """V1alpha1ApplicationSourceKustomize - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._common_labels = None
        self._images = None
        self._name_prefix = None
        self._name_suffix = None
        self._version = None
        self.discriminator = None

        if common_labels is not None:
            self.common_labels = common_labels
        if images is not None:
            self.images = images
        if name_prefix is not None:
            self.name_prefix = name_prefix
        if name_suffix is not None:
            self.name_suffix = name_suffix
        if version is not None:
            self.version = version

    @property
    def common_labels(self):
        """Gets the common_labels of this V1alpha1ApplicationSourceKustomize.  # noqa: E501


        :return: The common_labels of this V1alpha1ApplicationSourceKustomize.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._common_labels

    @common_labels.setter
    def common_labels(self, common_labels):
        """Sets the common_labels of this V1alpha1ApplicationSourceKustomize.


        :param common_labels: The common_labels of this V1alpha1ApplicationSourceKustomize.  # noqa: E501
        :type: dict(str, str)
        """

        self._common_labels = common_labels

    @property
    def images(self):
        """Gets the images of this V1alpha1ApplicationSourceKustomize.  # noqa: E501


        :return: The images of this V1alpha1ApplicationSourceKustomize.  # noqa: E501
        :rtype: list[str]
        """
        return self._images

    @images.setter
    def images(self, images):
        """Sets the images of this V1alpha1ApplicationSourceKustomize.


        :param images: The images of this V1alpha1ApplicationSourceKustomize.  # noqa: E501
        :type: list[str]
        """

        self._images = images

    @property
    def name_prefix(self):
        """Gets the name_prefix of this V1alpha1ApplicationSourceKustomize.  # noqa: E501


        :return: The name_prefix of this V1alpha1ApplicationSourceKustomize.  # noqa: E501
        :rtype: str
        """
        return self._name_prefix

    @name_prefix.setter
    def name_prefix(self, name_prefix):
        """Sets the name_prefix of this V1alpha1ApplicationSourceKustomize.


        :param name_prefix: The name_prefix of this V1alpha1ApplicationSourceKustomize.  # noqa: E501
        :type: str
        """

        self._name_prefix = name_prefix

    @property
    def name_suffix(self):
        """Gets the name_suffix of this V1alpha1ApplicationSourceKustomize.  # noqa: E501


        :return: The name_suffix of this V1alpha1ApplicationSourceKustomize.  # noqa: E501
        :rtype: str
        """
        return self._name_suffix

    @name_suffix.setter
    def name_suffix(self, name_suffix):
        """Sets the name_suffix of this V1alpha1ApplicationSourceKustomize.


        :param name_suffix: The name_suffix of this V1alpha1ApplicationSourceKustomize.  # noqa: E501
        :type: str
        """

        self._name_suffix = name_suffix

    @property
    def version(self):
        """Gets the version of this V1alpha1ApplicationSourceKustomize.  # noqa: E501


        :return: The version of this V1alpha1ApplicationSourceKustomize.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this V1alpha1ApplicationSourceKustomize.


        :param version: The version of this V1alpha1ApplicationSourceKustomize.  # noqa: E501
        :type: str
        """

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1ApplicationSourceKustomize):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1alpha1ApplicationSourceKustomize):
            return True

        return self.to_dict() != other.to_dict()
