# coding: utf-8
# Copyright (c) 2020, Globo (https://github.com/globocom)
# License: BSD-3-Clause

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from argocd_client.configuration import Configuration


class V1alpha1Repository(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'connection_state': 'V1alpha1ConnectionState',
        'enable_lfs': 'bool',
        'inherited_creds': 'bool',
        'insecure': 'bool',
        'insecure_ignore_host_key': 'bool',
        'name': 'str',
        'password': 'str',
        'repo': 'str',
        'ssh_private_key': 'str',
        'tls_client_cert_data': 'str',
        'tls_client_cert_key': 'str',
        'type': 'str',
        'username': 'str'
    }

    attribute_map = {
        'connection_state': 'connectionState',
        'enable_lfs': 'enableLfs',
        'inherited_creds': 'inheritedCreds',
        'insecure': 'insecure',
        'insecure_ignore_host_key': 'insecureIgnoreHostKey',
        'name': 'name',
        'password': 'password',
        'repo': 'repo',
        'ssh_private_key': 'sshPrivateKey',
        'tls_client_cert_data': 'tlsClientCertData',
        'tls_client_cert_key': 'tlsClientCertKey',
        'type': 'type',
        'username': 'username'
    }

    def __init__(self, connection_state=None, enable_lfs=None, inherited_creds=None, insecure=None, insecure_ignore_host_key=None, name=None, password=None, repo=None, ssh_private_key=None, tls_client_cert_data=None, tls_client_cert_key=None, type=None, username=None, local_vars_configuration=None):  # noqa: E501
        """V1alpha1Repository - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._connection_state = None
        self._enable_lfs = None
        self._inherited_creds = None
        self._insecure = None
        self._insecure_ignore_host_key = None
        self._name = None
        self._password = None
        self._repo = None
        self._ssh_private_key = None
        self._tls_client_cert_data = None
        self._tls_client_cert_key = None
        self._type = None
        self._username = None
        self.discriminator = None

        if connection_state is not None:
            self.connection_state = connection_state
        if enable_lfs is not None:
            self.enable_lfs = enable_lfs
        if inherited_creds is not None:
            self.inherited_creds = inherited_creds
        if insecure is not None:
            self.insecure = insecure
        if insecure_ignore_host_key is not None:
            self.insecure_ignore_host_key = insecure_ignore_host_key
        if name is not None:
            self.name = name
        if password is not None:
            self.password = password
        if repo is not None:
            self.repo = repo
        if ssh_private_key is not None:
            self.ssh_private_key = ssh_private_key
        if tls_client_cert_data is not None:
            self.tls_client_cert_data = tls_client_cert_data
        if tls_client_cert_key is not None:
            self.tls_client_cert_key = tls_client_cert_key
        if type is not None:
            self.type = type
        if username is not None:
            self.username = username

    @property
    def connection_state(self):
        """Gets the connection_state of this V1alpha1Repository.  # noqa: E501


        :return: The connection_state of this V1alpha1Repository.  # noqa: E501
        :rtype: V1alpha1ConnectionState
        """
        return self._connection_state

    @connection_state.setter
    def connection_state(self, connection_state):
        """Sets the connection_state of this V1alpha1Repository.


        :param connection_state: The connection_state of this V1alpha1Repository.  # noqa: E501
        :type: V1alpha1ConnectionState
        """

        self._connection_state = connection_state

    @property
    def enable_lfs(self):
        """Gets the enable_lfs of this V1alpha1Repository.  # noqa: E501


        :return: The enable_lfs of this V1alpha1Repository.  # noqa: E501
        :rtype: bool
        """
        return self._enable_lfs

    @enable_lfs.setter
    def enable_lfs(self, enable_lfs):
        """Sets the enable_lfs of this V1alpha1Repository.


        :param enable_lfs: The enable_lfs of this V1alpha1Repository.  # noqa: E501
        :type: bool
        """

        self._enable_lfs = enable_lfs

    @property
    def inherited_creds(self):
        """Gets the inherited_creds of this V1alpha1Repository.  # noqa: E501


        :return: The inherited_creds of this V1alpha1Repository.  # noqa: E501
        :rtype: bool
        """
        return self._inherited_creds

    @inherited_creds.setter
    def inherited_creds(self, inherited_creds):
        """Sets the inherited_creds of this V1alpha1Repository.


        :param inherited_creds: The inherited_creds of this V1alpha1Repository.  # noqa: E501
        :type: bool
        """

        self._inherited_creds = inherited_creds

    @property
    def insecure(self):
        """Gets the insecure of this V1alpha1Repository.  # noqa: E501


        :return: The insecure of this V1alpha1Repository.  # noqa: E501
        :rtype: bool
        """
        return self._insecure

    @insecure.setter
    def insecure(self, insecure):
        """Sets the insecure of this V1alpha1Repository.


        :param insecure: The insecure of this V1alpha1Repository.  # noqa: E501
        :type: bool
        """

        self._insecure = insecure

    @property
    def insecure_ignore_host_key(self):
        """Gets the insecure_ignore_host_key of this V1alpha1Repository.  # noqa: E501


        :return: The insecure_ignore_host_key of this V1alpha1Repository.  # noqa: E501
        :rtype: bool
        """
        return self._insecure_ignore_host_key

    @insecure_ignore_host_key.setter
    def insecure_ignore_host_key(self, insecure_ignore_host_key):
        """Sets the insecure_ignore_host_key of this V1alpha1Repository.


        :param insecure_ignore_host_key: The insecure_ignore_host_key of this V1alpha1Repository.  # noqa: E501
        :type: bool
        """

        self._insecure_ignore_host_key = insecure_ignore_host_key

    @property
    def name(self):
        """Gets the name of this V1alpha1Repository.  # noqa: E501


        :return: The name of this V1alpha1Repository.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this V1alpha1Repository.


        :param name: The name of this V1alpha1Repository.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def password(self):
        """Gets the password of this V1alpha1Repository.  # noqa: E501


        :return: The password of this V1alpha1Repository.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this V1alpha1Repository.


        :param password: The password of this V1alpha1Repository.  # noqa: E501
        :type: str
        """

        self._password = password

    @property
    def repo(self):
        """Gets the repo of this V1alpha1Repository.  # noqa: E501


        :return: The repo of this V1alpha1Repository.  # noqa: E501
        :rtype: str
        """
        return self._repo

    @repo.setter
    def repo(self, repo):
        """Sets the repo of this V1alpha1Repository.


        :param repo: The repo of this V1alpha1Repository.  # noqa: E501
        :type: str
        """

        self._repo = repo

    @property
    def ssh_private_key(self):
        """Gets the ssh_private_key of this V1alpha1Repository.  # noqa: E501


        :return: The ssh_private_key of this V1alpha1Repository.  # noqa: E501
        :rtype: str
        """
        return self._ssh_private_key

    @ssh_private_key.setter
    def ssh_private_key(self, ssh_private_key):
        """Sets the ssh_private_key of this V1alpha1Repository.


        :param ssh_private_key: The ssh_private_key of this V1alpha1Repository.  # noqa: E501
        :type: str
        """

        self._ssh_private_key = ssh_private_key

    @property
    def tls_client_cert_data(self):
        """Gets the tls_client_cert_data of this V1alpha1Repository.  # noqa: E501


        :return: The tls_client_cert_data of this V1alpha1Repository.  # noqa: E501
        :rtype: str
        """
        return self._tls_client_cert_data

    @tls_client_cert_data.setter
    def tls_client_cert_data(self, tls_client_cert_data):
        """Sets the tls_client_cert_data of this V1alpha1Repository.


        :param tls_client_cert_data: The tls_client_cert_data of this V1alpha1Repository.  # noqa: E501
        :type: str
        """

        self._tls_client_cert_data = tls_client_cert_data

    @property
    def tls_client_cert_key(self):
        """Gets the tls_client_cert_key of this V1alpha1Repository.  # noqa: E501


        :return: The tls_client_cert_key of this V1alpha1Repository.  # noqa: E501
        :rtype: str
        """
        return self._tls_client_cert_key

    @tls_client_cert_key.setter
    def tls_client_cert_key(self, tls_client_cert_key):
        """Sets the tls_client_cert_key of this V1alpha1Repository.


        :param tls_client_cert_key: The tls_client_cert_key of this V1alpha1Repository.  # noqa: E501
        :type: str
        """

        self._tls_client_cert_key = tls_client_cert_key

    @property
    def type(self):
        """Gets the type of this V1alpha1Repository.  # noqa: E501


        :return: The type of this V1alpha1Repository.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this V1alpha1Repository.


        :param type: The type of this V1alpha1Repository.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def username(self):
        """Gets the username of this V1alpha1Repository.  # noqa: E501


        :return: The username of this V1alpha1Repository.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this V1alpha1Repository.


        :param username: The username of this V1alpha1Repository.  # noqa: E501
        :type: str
        """

        self._username = username

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1Repository):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1alpha1Repository):
            return True

        return self.to_dict() != other.to_dict()
