# coding: utf-8
# Copyright (c) 2020, Globo (https://github.com/globocom)
# License: BSD-3-Clause

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from argocd_client.configuration import Configuration


class V1alpha1AWSAuthConfig(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'cluster_name': 'str',
        'role_arn': 'str'
    }

    attribute_map = {
        'cluster_name': 'clusterName',
        'role_arn': 'roleARN'
    }

    def __init__(self, cluster_name=None, role_arn=None, local_vars_configuration=None):  # noqa: E501
        """V1alpha1AWSAuthConfig - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._cluster_name = None
        self._role_arn = None
        self.discriminator = None

        if cluster_name is not None:
            self.cluster_name = cluster_name
        if role_arn is not None:
            self.role_arn = role_arn

    @property
    def cluster_name(self):
        """Gets the cluster_name of this V1alpha1AWSAuthConfig.  # noqa: E501


        :return: The cluster_name of this V1alpha1AWSAuthConfig.  # noqa: E501
        :rtype: str
        """
        return self._cluster_name

    @cluster_name.setter
    def cluster_name(self, cluster_name):
        """Sets the cluster_name of this V1alpha1AWSAuthConfig.


        :param cluster_name: The cluster_name of this V1alpha1AWSAuthConfig.  # noqa: E501
        :type: str
        """

        self._cluster_name = cluster_name

    @property
    def role_arn(self):
        """Gets the role_arn of this V1alpha1AWSAuthConfig.  # noqa: E501

        RoleARN contains optional role ARN. If set then AWS IAM Authenticator assume a role to perform cluster operations instead of the default AWS credential provider chain.  # noqa: E501

        :return: The role_arn of this V1alpha1AWSAuthConfig.  # noqa: E501
        :rtype: str
        """
        return self._role_arn

    @role_arn.setter
    def role_arn(self, role_arn):
        """Sets the role_arn of this V1alpha1AWSAuthConfig.

        RoleARN contains optional role ARN. If set then AWS IAM Authenticator assume a role to perform cluster operations instead of the default AWS credential provider chain.  # noqa: E501

        :param role_arn: The role_arn of this V1alpha1AWSAuthConfig.  # noqa: E501
        :type: str
        """

        self._role_arn = role_arn

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1AWSAuthConfig):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1alpha1AWSAuthConfig):
            return True

        return self.to_dict() != other.to_dict()
