# coding: utf-8
# Copyright (c) 2020, Globo (https://github.com/globocom)
# License: BSD-3-Clause

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from argocd_client.configuration import Configuration


class V1alpha1ResourceAction(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'disabled': 'bool',
        'name': 'str',
        'params': 'list[V1alpha1ResourceActionParam]'
    }

    attribute_map = {
        'disabled': 'disabled',
        'name': 'name',
        'params': 'params'
    }

    def __init__(self, disabled=None, name=None, params=None, local_vars_configuration=None):  # noqa: E501
        """V1alpha1ResourceAction - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._disabled = None
        self._name = None
        self._params = None
        self.discriminator = None

        if disabled is not None:
            self.disabled = disabled
        if name is not None:
            self.name = name
        if params is not None:
            self.params = params

    @property
    def disabled(self):
        """Gets the disabled of this V1alpha1ResourceAction.  # noqa: E501


        :return: The disabled of this V1alpha1ResourceAction.  # noqa: E501
        :rtype: bool
        """
        return self._disabled

    @disabled.setter
    def disabled(self, disabled):
        """Sets the disabled of this V1alpha1ResourceAction.


        :param disabled: The disabled of this V1alpha1ResourceAction.  # noqa: E501
        :type: bool
        """

        self._disabled = disabled

    @property
    def name(self):
        """Gets the name of this V1alpha1ResourceAction.  # noqa: E501


        :return: The name of this V1alpha1ResourceAction.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this V1alpha1ResourceAction.


        :param name: The name of this V1alpha1ResourceAction.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def params(self):
        """Gets the params of this V1alpha1ResourceAction.  # noqa: E501


        :return: The params of this V1alpha1ResourceAction.  # noqa: E501
        :rtype: list[V1alpha1ResourceActionParam]
        """
        return self._params

    @params.setter
    def params(self, params):
        """Sets the params of this V1alpha1ResourceAction.


        :param params: The params of this V1alpha1ResourceAction.  # noqa: E501
        :type: list[V1alpha1ResourceActionParam]
        """

        self._params = params

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1ResourceAction):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1alpha1ResourceAction):
            return True

        return self.to_dict() != other.to_dict()
