# coding: utf-8
# Copyright (c) 2020, Globo (https://github.com/globocom)
# License: BSD-3-Clause

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from argocd_client.configuration import Configuration


class V1alpha1RevisionHistory(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'deploy_started_at': 'V1Time',
        'deployed_at': 'V1Time',
        'id': 'str',
        'revision': 'str',
        'source': 'V1alpha1ApplicationSource'
    }

    attribute_map = {
        'deploy_started_at': 'deployStartedAt',
        'deployed_at': 'deployedAt',
        'id': 'id',
        'revision': 'revision',
        'source': 'source'
    }

    def __init__(self, deploy_started_at=None, deployed_at=None, id=None, revision=None, source=None, local_vars_configuration=None):  # noqa: E501
        """V1alpha1RevisionHistory - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._deploy_started_at = None
        self._deployed_at = None
        self._id = None
        self._revision = None
        self._source = None
        self.discriminator = None

        if deploy_started_at is not None:
            self.deploy_started_at = deploy_started_at
        if deployed_at is not None:
            self.deployed_at = deployed_at
        if id is not None:
            self.id = id
        if revision is not None:
            self.revision = revision
        if source is not None:
            self.source = source

    @property
    def deploy_started_at(self):
        """Gets the deploy_started_at of this V1alpha1RevisionHistory.  # noqa: E501


        :return: The deploy_started_at of this V1alpha1RevisionHistory.  # noqa: E501
        :rtype: V1Time
        """
        return self._deploy_started_at

    @deploy_started_at.setter
    def deploy_started_at(self, deploy_started_at):
        """Sets the deploy_started_at of this V1alpha1RevisionHistory.


        :param deploy_started_at: The deploy_started_at of this V1alpha1RevisionHistory.  # noqa: E501
        :type: V1Time
        """

        self._deploy_started_at = deploy_started_at

    @property
    def deployed_at(self):
        """Gets the deployed_at of this V1alpha1RevisionHistory.  # noqa: E501


        :return: The deployed_at of this V1alpha1RevisionHistory.  # noqa: E501
        :rtype: V1Time
        """
        return self._deployed_at

    @deployed_at.setter
    def deployed_at(self, deployed_at):
        """Sets the deployed_at of this V1alpha1RevisionHistory.


        :param deployed_at: The deployed_at of this V1alpha1RevisionHistory.  # noqa: E501
        :type: V1Time
        """

        self._deployed_at = deployed_at

    @property
    def id(self):
        """Gets the id of this V1alpha1RevisionHistory.  # noqa: E501


        :return: The id of this V1alpha1RevisionHistory.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this V1alpha1RevisionHistory.


        :param id: The id of this V1alpha1RevisionHistory.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def revision(self):
        """Gets the revision of this V1alpha1RevisionHistory.  # noqa: E501


        :return: The revision of this V1alpha1RevisionHistory.  # noqa: E501
        :rtype: str
        """
        return self._revision

    @revision.setter
    def revision(self, revision):
        """Sets the revision of this V1alpha1RevisionHistory.


        :param revision: The revision of this V1alpha1RevisionHistory.  # noqa: E501
        :type: str
        """

        self._revision = revision

    @property
    def source(self):
        """Gets the source of this V1alpha1RevisionHistory.  # noqa: E501


        :return: The source of this V1alpha1RevisionHistory.  # noqa: E501
        :rtype: V1alpha1ApplicationSource
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this V1alpha1RevisionHistory.


        :param source: The source of this V1alpha1RevisionHistory.  # noqa: E501
        :type: V1alpha1ApplicationSource
        """

        self._source = source

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1RevisionHistory):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1alpha1RevisionHistory):
            return True

        return self.to_dict() != other.to_dict()
