# coding: utf-8
# Copyright (c) 2020, Globo (https://github.com/globocom)
# License: BSD-3-Clause

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from argocd_client.configuration import Configuration


class V1alpha1ApplicationTree(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'nodes': 'list[V1alpha1ResourceNode]',
        'orphaned_nodes': 'list[V1alpha1ResourceNode]'
    }

    attribute_map = {
        'nodes': 'nodes',
        'orphaned_nodes': 'orphanedNodes'
    }

    def __init__(self, nodes=None, orphaned_nodes=None, local_vars_configuration=None):  # noqa: E501
        """V1alpha1ApplicationTree - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._nodes = None
        self._orphaned_nodes = None
        self.discriminator = None

        if nodes is not None:
            self.nodes = nodes
        if orphaned_nodes is not None:
            self.orphaned_nodes = orphaned_nodes

    @property
    def nodes(self):
        """Gets the nodes of this V1alpha1ApplicationTree.  # noqa: E501

        Nodes contains list of nodes which either directly managed by the application and children of directly managed nodes.  # noqa: E501

        :return: The nodes of this V1alpha1ApplicationTree.  # noqa: E501
        :rtype: list[V1alpha1ResourceNode]
        """
        return self._nodes

    @nodes.setter
    def nodes(self, nodes):
        """Sets the nodes of this V1alpha1ApplicationTree.

        Nodes contains list of nodes which either directly managed by the application and children of directly managed nodes.  # noqa: E501

        :param nodes: The nodes of this V1alpha1ApplicationTree.  # noqa: E501
        :type: list[V1alpha1ResourceNode]
        """

        self._nodes = nodes

    @property
    def orphaned_nodes(self):
        """Gets the orphaned_nodes of this V1alpha1ApplicationTree.  # noqa: E501

        OrphanedNodes contains if or orphaned nodes: nodes which are not managed by the app but in the same namespace. List is populated only if orphaned resources enabled in app project.  # noqa: E501

        :return: The orphaned_nodes of this V1alpha1ApplicationTree.  # noqa: E501
        :rtype: list[V1alpha1ResourceNode]
        """
        return self._orphaned_nodes

    @orphaned_nodes.setter
    def orphaned_nodes(self, orphaned_nodes):
        """Sets the orphaned_nodes of this V1alpha1ApplicationTree.

        OrphanedNodes contains if or orphaned nodes: nodes which are not managed by the app but in the same namespace. List is populated only if orphaned resources enabled in app project.  # noqa: E501

        :param orphaned_nodes: The orphaned_nodes of this V1alpha1ApplicationTree.  # noqa: E501
        :type: list[V1alpha1ResourceNode]
        """

        self._orphaned_nodes = orphaned_nodes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1ApplicationTree):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1alpha1ApplicationTree):
            return True

        return self.to_dict() != other.to_dict()
