# coding: utf-8
# Copyright (c) 2020, Globo (https://github.com/globocom)
# License: BSD-3-Clause

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from argocd_client.configuration import Configuration


class V1alpha1ConnectionState(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'attempted_at': 'V1Time',
        'message': 'str',
        'status': 'str'
    }

    attribute_map = {
        'attempted_at': 'attemptedAt',
        'message': 'message',
        'status': 'status'
    }

    def __init__(self, attempted_at=None, message=None, status=None, local_vars_configuration=None):  # noqa: E501
        """V1alpha1ConnectionState - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._attempted_at = None
        self._message = None
        self._status = None
        self.discriminator = None

        if attempted_at is not None:
            self.attempted_at = attempted_at
        if message is not None:
            self.message = message
        if status is not None:
            self.status = status

    @property
    def attempted_at(self):
        """Gets the attempted_at of this V1alpha1ConnectionState.  # noqa: E501


        :return: The attempted_at of this V1alpha1ConnectionState.  # noqa: E501
        :rtype: V1Time
        """
        return self._attempted_at

    @attempted_at.setter
    def attempted_at(self, attempted_at):
        """Sets the attempted_at of this V1alpha1ConnectionState.


        :param attempted_at: The attempted_at of this V1alpha1ConnectionState.  # noqa: E501
        :type: V1Time
        """

        self._attempted_at = attempted_at

    @property
    def message(self):
        """Gets the message of this V1alpha1ConnectionState.  # noqa: E501


        :return: The message of this V1alpha1ConnectionState.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this V1alpha1ConnectionState.


        :param message: The message of this V1alpha1ConnectionState.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def status(self):
        """Gets the status of this V1alpha1ConnectionState.  # noqa: E501


        :return: The status of this V1alpha1ConnectionState.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this V1alpha1ConnectionState.


        :param status: The status of this V1alpha1ConnectionState.  # noqa: E501
        :type: str
        """

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1ConnectionState):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1alpha1ConnectionState):
            return True

        return self.to_dict() != other.to_dict()
