# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from argocd_client.configuration import Configuration


class V1alpha1ResourceNetworkingInfo(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'external_ur_ls': 'list[str]',
        'ingress': 'list[V1LoadBalancerIngress]',
        'labels': 'dict(str, str)',
        'target_labels': 'dict(str, str)',
        'target_refs': 'list[V1alpha1ResourceRef]'
    }

    attribute_map = {
        'external_ur_ls': 'externalURLs',
        'ingress': 'ingress',
        'labels': 'labels',
        'target_labels': 'targetLabels',
        'target_refs': 'targetRefs'
    }

    def __init__(self, external_ur_ls=None, ingress=None, labels=None, target_labels=None, target_refs=None, local_vars_configuration=None):  # noqa: E501
        """V1alpha1ResourceNetworkingInfo - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._external_ur_ls = None
        self._ingress = None
        self._labels = None
        self._target_labels = None
        self._target_refs = None
        self.discriminator = None

        if external_ur_ls is not None:
            self.external_ur_ls = external_ur_ls
        if ingress is not None:
            self.ingress = ingress
        if labels is not None:
            self.labels = labels
        if target_labels is not None:
            self.target_labels = target_labels
        if target_refs is not None:
            self.target_refs = target_refs

    @property
    def external_ur_ls(self):
        """Gets the external_ur_ls of this V1alpha1ResourceNetworkingInfo.  # noqa: E501

        ExternalURLs holds list of URLs which should be available externally. List is populated for ingress resources using rules hostnames.  # noqa: E501

        :return: The external_ur_ls of this V1alpha1ResourceNetworkingInfo.  # noqa: E501
        :rtype: list[str]
        """
        return self._external_ur_ls

    @external_ur_ls.setter
    def external_ur_ls(self, external_ur_ls):
        """Sets the external_ur_ls of this V1alpha1ResourceNetworkingInfo.

        ExternalURLs holds list of URLs which should be available externally. List is populated for ingress resources using rules hostnames.  # noqa: E501

        :param external_ur_ls: The external_ur_ls of this V1alpha1ResourceNetworkingInfo.  # noqa: E501
        :type: list[str]
        """

        self._external_ur_ls = external_ur_ls

    @property
    def ingress(self):
        """Gets the ingress of this V1alpha1ResourceNetworkingInfo.  # noqa: E501


        :return: The ingress of this V1alpha1ResourceNetworkingInfo.  # noqa: E501
        :rtype: list[V1LoadBalancerIngress]
        """
        return self._ingress

    @ingress.setter
    def ingress(self, ingress):
        """Sets the ingress of this V1alpha1ResourceNetworkingInfo.


        :param ingress: The ingress of this V1alpha1ResourceNetworkingInfo.  # noqa: E501
        :type: list[V1LoadBalancerIngress]
        """

        self._ingress = ingress

    @property
    def labels(self):
        """Gets the labels of this V1alpha1ResourceNetworkingInfo.  # noqa: E501


        :return: The labels of this V1alpha1ResourceNetworkingInfo.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._labels

    @labels.setter
    def labels(self, labels):
        """Sets the labels of this V1alpha1ResourceNetworkingInfo.


        :param labels: The labels of this V1alpha1ResourceNetworkingInfo.  # noqa: E501
        :type: dict(str, str)
        """

        self._labels = labels

    @property
    def target_labels(self):
        """Gets the target_labels of this V1alpha1ResourceNetworkingInfo.  # noqa: E501


        :return: The target_labels of this V1alpha1ResourceNetworkingInfo.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._target_labels

    @target_labels.setter
    def target_labels(self, target_labels):
        """Sets the target_labels of this V1alpha1ResourceNetworkingInfo.


        :param target_labels: The target_labels of this V1alpha1ResourceNetworkingInfo.  # noqa: E501
        :type: dict(str, str)
        """

        self._target_labels = target_labels

    @property
    def target_refs(self):
        """Gets the target_refs of this V1alpha1ResourceNetworkingInfo.  # noqa: E501


        :return: The target_refs of this V1alpha1ResourceNetworkingInfo.  # noqa: E501
        :rtype: list[V1alpha1ResourceRef]
        """
        return self._target_refs

    @target_refs.setter
    def target_refs(self, target_refs):
        """Sets the target_refs of this V1alpha1ResourceNetworkingInfo.


        :param target_refs: The target_refs of this V1alpha1ResourceNetworkingInfo.  # noqa: E501
        :type: list[V1alpha1ResourceRef]
        """

        self._target_refs = target_refs

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1ResourceNetworkingInfo):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1alpha1ResourceNetworkingInfo):
            return True

        return self.to_dict() != other.to_dict()
